### ISSUE TITLE
Unable to login for the first time w/ error:  System.IO.IOException: Permission denied`

### ISSUE THREAD

**Issue by cameronj86** [jberlyn/kosync-dotnet#4]
`Connection id "redacted", Request id "redacted:00000001": An unhandled exception was thrown by the application.
kosync  |       System.UnauthorizedAccessException: Access to the path '/app/data/Kosync.db' is denied.
kosync  |        ---> System.IO.IOException: Permission denied`

Admin pw removed from docker-compose file, while port added to docker file. Everything else is stock.

**Comment by jberlyn** [comment]
Hey @cameronj86,

Does this still happen on the latest version `v1.2.1`?

**Comment by jberlyn** [comment]
Closing this out, reach out if it is still a problem.

**Comment by snrubthinks** [comment]
I had this issue as well. I'm using a bind mount volume for the data directory but the data directory was created by the container with `root:root` ownership. So when it would try to create the DB as `1000:1000`, it would fail.

Removing the `user: 1000:1000` line worked around the issue, although that keeps the permissions as root of course.

docker-compose.yml:
```
name: kosync-dotnet
services:
  kosync:
    container_name: kosync-dotnet
    # v1.5.0
    image: ghcr.io/jberlyn/kosync-dotnet@sha256:98805f11ab5cab2e472823664f21adc6582b1a44850ebe2c607b4adc12327587
    network_mode: host
    restart: unless-stopped
    volumes:
      - /containers/appdata/kosync-dotnet/data:/app/data
    environment:
      - REGISTRATION_DISABLED=false
      - ASPNETCORE_HTTP_PORTS=24236
    user: 1000:1000
```
